// Auto-generated Error Code Enum and Message Map
// Generated at: 2025-07-08T04:31:25.478473Z

export enum ErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_EXISTS = "EMAIL_EXISTS",
  INVALID_TOKEN = "INVALID_TOKEN",
  MISSING_REFRESH_TOKEN = "MISSING_REFRESH_TOKEN",
  TOKEN_REPLAYED = "TOKEN_REPLAYED",
  TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",
  WEAK_PASSWORD = "WEAK_PASSWORD",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  INVALID_OTP = "INVALID_OTP",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_ALREADY_USED = "OTP_ALREADY_USED",
  OTP_TOO_MANY_RESEND = "OTP_TOO_MANY_RESEND",
  OTP_TOO_MANY_ATTEMPTS = "OTP_TOO_MANY_ATTEMPTS",
  OTP_BLOCKED = "OTP_BLOCKED",
  OTP_NOT_FOUND = "OTP_NOT_FOUND",
  VERSION_CONFLICT = "VERSION_CONFLICT",
  ACCESS_DENIED = "ACCESS_DENIED",
  CHECKLIST_NOT_FOUND = "CHECKLIST_NOT_FOUND",
  MAX_CHECK_LIMIT_EXCEEDED = "MAX_CHECK_LIMIT_EXCEEDED",
  CHECKLIST_CONTENT_INVALID = "CHECKLIST_CONTENT_INVALID",
  CHECK_NOT_FOUND = "CHECK_NOT_FOUND",
  CHECK_EMPTY = "CHECK_EMPTY",
}

export const ErrorMessages: Record<ErrorCode, { status: number, message: string, hint: string }> = {
  [ErrorCode.INVALID_CREDENTIALS]: { status: 401, message: "Email hoặc mật khẩu không đúng", hint: "Kiểm tra lại thông tin đăng nhập" },
  [ErrorCode.EMAIL_EXISTS]: { status: 409, message: "Email đã tồn tại", hint: "Dùng email khác hoặc đăng nhập nếu đã có tài khoản" },
  [ErrorCode.INVALID_TOKEN]: { status: 401, message: "Token không hợp lệ hoặc đã hết hạn", hint: "Vui lòng đăng nhập lại để nhận token mới" },
  [ErrorCode.MISSING_REFRESH_TOKEN]: { status: 400, message: "Thiếu refresh token", hint: "Đảm bảo gửi kèm refresh token trong request" },
  [ErrorCode.TOKEN_REPLAYED]: { status: 401, message: "Refresh token đã bị dùng lại", hint: "Đăng nhập lại để nhận token mới" },
  [ErrorCode.TOO_MANY_ATTEMPTS]: { status: 429, message: "Gửi OTP hoặc xác thực quá nhiều lần", hint: "Thử lại sau vài phút" },
  [ErrorCode.WEAK_PASSWORD]: { status: 400, message: "Mật khẩu yếu", hint: "Mật khẩu phải chứa chữ hoa, chữ thường và số" },
  [ErrorCode.USER_NOT_FOUND]: { status: 404, message: "Không tìm thấy người dùng", hint: "Đảm bảo bạn đã đăng ký tài khoản đúng email" },
  [ErrorCode.EMAIL_NOT_VERIFIED]: { status: 403, message: "Email chưa được xác thực", hint: "Kiểm tra email để xác thực tài khoản" },
  [ErrorCode.INVALID_OTP]: { status: 400, message: "OTP sai hoặc hết hạn", hint: "Bạn có thể yêu cầu gửi lại mã xác thực" },
  [ErrorCode.OTP_EXPIRED]: { status: 400, message: "Mã OTP đã hết hạn", hint: "Yêu cầu gửi lại mã OTP mới" },
  [ErrorCode.OTP_ALREADY_USED]: { status: 400, message: "Mã OTP đã được sử dụng", hint: "Vui lòng yêu cầu mã OTP mới" },
  [ErrorCode.OTP_TOO_MANY_RESEND]: { status: 429, message: "Gửi lại OTP quá nhiều lần", hint: "Thử lại sau vài phút" },
  [ErrorCode.OTP_TOO_MANY_ATTEMPTS]: { status: 429, message: "Nhập sai mã OTP quá nhiều lần", hint: "Tài khoản sẽ bị khóa tạm thời nếu tiếp tục" },
  [ErrorCode.OTP_BLOCKED]: { status: 423, message: "Tài khoản bị khóa tạm thời do sai mã nhiều", hint: "Đợi một thời gian rồi thử lại hoặc liên hệ hỗ trợ" },
  [ErrorCode.OTP_NOT_FOUND]: { status: 404, message: "Không tìm thấy mã OTP nào hợp lệ", hint: "Vui lòng yêu cầu gửi lại mã xác thực" },
  [ErrorCode.VERSION_CONFLICT]: { status: 409, message: "Save checklist với version cũ hơn", hint: "Reload checklist để lấy version mới nhất" },
  [ErrorCode.ACCESS_DENIED]: { status: 403, message: "Không có quyền truy cập checklist này", hint: "Hãy kiểm tra lại quyền sở hữu hoặc đăng nhập tài khoản đúng" },
  [ErrorCode.CHECKLIST_NOT_FOUND]: { status: 404, message: "Không tìm thấy checklist", hint: "ID checklist không tồn tại hoặc đã bị xóa" },
  [ErrorCode.MAX_CHECK_LIMIT_EXCEEDED]: { status: 400, message: "Checklist đã có quá nhiều công việc", hint: "Không thể thêm công việc mới, đã vượt giới hạn cho phép" },
  [ErrorCode.CHECKLIST_CONTENT_INVALID]: { status: 400, message: "Nội dung checklist không hợp lệ", hint: "Đảm bảo tiêu đề và nội dung checklist không trống hoặc sai định dạng" },
  [ErrorCode.CHECK_NOT_FOUND]: { status: 404, message: "Không tìm thấy công việc trong checklist", hint: "ID công việc không tồn tại trong checklist" },
  [ErrorCode.CHECK_EMPTY]: { status: 400, message: "Nội dung công việc không được để trống", hint: "Nhập nội dung công việc trước khi lưu" },
};
